# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\designs\MainMenuPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1116, 823))
        self.centralwidget.setMaximumSize(QtCore.QSize(1116, 823))
        self.centralwidget.setObjectName("centralwidget")
        self.widget_MenuButtons = QtWidgets.QWidget(self.centralwidget)
        self.widget_MenuButtons.setGeometry(QtCore.QRect(10, 130, 1081, 71))
        self.widget_MenuButtons.setMinimumSize(QtCore.QSize(761, 71))
        self.widget_MenuButtons.setObjectName("widget_MenuButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_MenuButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_BotVBot = QtWidgets.QPushButton(self.widget_MenuButtons)
        self.pushButton_BotVBot.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_BotVBot.setFont(font)
        self.pushButton_BotVBot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_BotVBot.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_BotVBot.setStyleSheet("QPushButton {\n"
                                              "                background-color: #5A9; \n"
                                              "                color: white; \n"
                                              "                padding: 10px 20px; \n"
                                              "                border: 2px solid #476;\n"
                                              "                border-radius: 10px;\n"
                                              "                font-size: 16px;\n"
                                              "                font-weight: bold;\n"
                                              "                box-shadow: 3px 3px 5px #888888;\n"
                                              "                transition: background-color 0.3s, transform 0.3s;\n"
                                              "            }\n"
                                              "            QPushButton:hover {\n"
                                              "                background-color: #476;\n"
                                              "                transform: scale(1.05);\n"
                                              "            }\n"
                                              "            QPushButton:pressed {\n"
                                              "                background-color: #354;\n"
                                              "                transform: scale(0.95);\n"
                                              "            }")
        self.pushButton_BotVBot.setCheckable(False)
        self.pushButton_BotVBot.setAutoDefault(False)
        self.pushButton_BotVBot.setDefault(False)
        self.pushButton_BotVBot.setFlat(False)
        self.pushButton_BotVBot.setObjectName("pushButton_BotVBot")
        self.horizontalLayout_2.addWidget(self.pushButton_BotVBot)
        self.pushButton_AboutGo = QtWidgets.QPushButton(self.widget_MenuButtons)
        self.pushButton_AboutGo.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_AboutGo.setFont(font)
        self.pushButton_AboutGo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_AboutGo.setStyleSheet("QPushButton {\n"
                                              "                background-color: #5A9; \n"
                                              "                color: white; \n"
                                              "                padding: 10px 20px; \n"
                                              "                border: 2px solid #476;\n"
                                              "                border-radius: 10px;\n"
                                              "                font-size: 16px;\n"
                                              "                font-weight: bold;\n"
                                              "                box-shadow: 3px 3px 5px #888888;\n"
                                              "                transition: background-color 0.3s, transform 0.3s;\n"
                                              "            }\n"
                                              "            QPushButton:hover {\n"
                                              "                background-color: #476;\n"
                                              "                transform: scale(1.05);\n"
                                              "            }\n"
                                              "            QPushButton:pressed {\n"
                                              "                background-color: #354;\n"
                                              "                transform: scale(0.95);\n"
                                              "            }")
        self.pushButton_AboutGo.setAutoDefault(True)
        self.pushButton_AboutGo.setDefault(False)
        self.pushButton_AboutGo.setFlat(False)
        self.pushButton_AboutGo.setObjectName("pushButton_AboutGo")
        self.horizontalLayout_2.addWidget(self.pushButton_AboutGo)
        self.pushButton_PlayerVSBot = QtWidgets.QPushButton(self.widget_MenuButtons)
        self.pushButton_PlayerVSBot.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_PlayerVSBot.setFont(font)
        self.pushButton_PlayerVSBot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_PlayerVSBot.setStyleSheet("QPushButton {\n"
                                                  "                background-color: #5A9; \n"
                                                  "                color: white; \n"
                                                  "                padding: 10px 20px; \n"
                                                  "                border: 2px solid #476;\n"
                                                  "                border-radius: 10px;\n"
                                                  "                font-size: 16px;\n"
                                                  "                font-weight: bold;\n"
                                                  "                box-shadow: 3px 3px 5px #888888;\n"
                                                  "                transition: background-color 0.3s, transform 0.3s;\n"
                                                  "            }\n"
                                                  "            QPushButton:hover {\n"
                                                  "                background-color: #476;\n"
                                                  "                transform: scale(1.05);\n"
                                                  "            }\n"
                                                  "            QPushButton:pressed {\n"
                                                  "                background-color: #354;\n"
                                                  "                transform: scale(0.95);\n"
                                                  "            }")
        self.pushButton_PlayerVSBot.setAutoDefault(False)
        self.pushButton_PlayerVSBot.setDefault(False)
        self.pushButton_PlayerVSBot.setFlat(False)
        self.pushButton_PlayerVSBot.setObjectName("pushButton_PlayerVSBot")
        self.horizontalLayout_2.addWidget(self.pushButton_PlayerVSBot)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1111, 141))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
                                 "                font-size: 30px;\n"
                                 "                font-weight: bold;\n"
                                 "                color: rgb(70, 70, 70);\n"
                                 "                padding: 20px;\n"
                                 "\n"
                                 "            }")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 210, 1101, 581))
        self.stackedWidget.setMinimumSize(QtCore.QSize(751, 341))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1101, 611))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("/* QRadioButton Styles */\n"
                                         "QRadioButton {\n"
                                         "    font-size: 14px;\n"
                                         "    color: #5A9; \n"
                                         "    padding: 5px;\n"
                                         "}\n"
                                         "\n"
                                         "QRadioButton::indicator {\n"
                                         "    width: 15px;\n"
                                         "    height: 15px;\n"
                                         "    border-radius: 7.5px;\n"
                                         "}\n"
                                         "\n"
                                         "QRadioButton::indicator::unchecked {\n"
                                         "    border: 2px solid #2E8B57;\n"
                                         "    background-color: #FFFFFF;\n"
                                         "}\n"
                                         "\n"
                                         "QRadioButton::indicator::checked {\n"
                                         "    border: 2px solid #2E8B57;\n"
                                         "    background-color: #5A9; \n"
                                         "}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Hello = QtWidgets.QWidget()
        self.page_Hello.setObjectName("page_Hello")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_Hello)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 1071, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1067, 567))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1071, 571))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\gui\\designs\\../../../Background.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_Hello)
        self.page_AboutGo = QtWidgets.QWidget()
        self.page_AboutGo.setObjectName("page_AboutGo")
        self.splitter = QtWidgets.QSplitter(self.page_AboutGo)
        self.splitter.setGeometry(QtCore.QRect(15, 90, 1061, 461))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(291, 261))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\gui\\designs\\../../../Picture2.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setMaximumSize(QtCore.QSize(291, 261))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(".\\gui\\designs\\../../../Picture3.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setMaximumSize(QtCore.QSize(291, 261))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(".\\gui\\designs\\../../../Picture4.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowser.setMaximumSize(QtCore.QSize(301, 121))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(301, 121))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_4.addWidget(self.textBrowser_2, 0, 1, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowser_3.setMaximumSize(QtCore.QSize(311, 121))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_4.addWidget(self.textBrowser_3, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_AboutGo)
        self.page_CreateSGF = QtWidgets.QWidget()
        self.page_CreateSGF.setObjectName("page_CreateSGF")
        self.label_CreateSGF = QtWidgets.QLabel(self.page_CreateSGF)
        self.label_CreateSGF.setGeometry(QtCore.QRect(190, 30, 731, 81))
        self.label_CreateSGF.setMinimumSize(QtCore.QSize(731, 41))
        self.label_CreateSGF.setStyleSheet("QLabel {\n"
                                           "                font-size: 24px;\n"
                                           "                font-weight: bold;\n"
                                           "                color: #476;\n"
                                           "                padding: 20px;\n"
                                           "                background-color: #F0F0F0;\n"
                                           "            }")
        self.label_CreateSGF.setScaledContents(True)
        self.label_CreateSGF.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CreateSGF.setWordWrap(True)
        self.label_CreateSGF.setObjectName("label_CreateSGF")
        self.pushButton_CreateOk = QtWidgets.QPushButton(self.page_CreateSGF)
        self.pushButton_CreateOk.setGeometry(QtCore.QRect(530, 450, 75, 41))
        self.pushButton_CreateOk.setObjectName("pushButton_CreateOk")
        self.layoutWidget = QtWidgets.QWidget(self.page_CreateSGF)
        self.layoutWidget.setGeometry(QtCore.QRect(430, 340, 498, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(91, 41))
        self.label_4.setMaximumSize(QtCore.QSize(91, 41))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBox_BoardSize = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_BoardSize.setMinimumSize(QtCore.QSize(56, 41))
        self.spinBox_BoardSize.setMaximumSize(QtCore.QSize(56, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_BoardSize.setFont(font)
        self.spinBox_BoardSize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_BoardSize.setReadOnly(False)
        self.spinBox_BoardSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_BoardSize.setSpecialValueText("")
        self.spinBox_BoardSize.setMinimum(9)
        self.spinBox_BoardSize.setMaximum(19)
        self.spinBox_BoardSize.setSingleStep(4)
        self.spinBox_BoardSize.setObjectName("spinBox_BoardSize")
        self.horizontalLayout.addWidget(self.spinBox_BoardSize)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(90, 41))
        self.label_5.setMaximumSize(QtCore.QSize(90, 41))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.spinBox_Handicap = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_Handicap.setMinimumSize(QtCore.QSize(56, 41))
        self.spinBox_Handicap.setMaximumSize(QtCore.QSize(56, 41))
        self.spinBox_Handicap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_Handicap.setMouseTracking(True)
        self.spinBox_Handicap.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.spinBox_Handicap.setWrapping(True)
        self.spinBox_Handicap.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_Handicap.setSuffix("")
        self.spinBox_Handicap.setObjectName("spinBox_Handicap")
        self.horizontalLayout.addWidget(self.spinBox_Handicap)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(90, 41))
        self.label_6.setMaximumSize(QtCore.QSize(90, 41))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.doubleSpinBox_Komi = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_Komi.setMinimumSize(QtCore.QSize(83, 41))
        self.doubleSpinBox_Komi.setMaximumSize(QtCore.QSize(83, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.doubleSpinBox_Komi.setFont(font)
        self.doubleSpinBox_Komi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doubleSpinBox_Komi.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleSpinBox_Komi.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.doubleSpinBox_Komi.setAcceptDrops(False)
        self.doubleSpinBox_Komi.setAutoFillBackground(True)
        self.doubleSpinBox_Komi.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.doubleSpinBox_Komi.setWrapping(True)
        self.doubleSpinBox_Komi.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox_Komi.setDecimals(1)
        self.doubleSpinBox_Komi.setMinimum(-1444.0)
        self.doubleSpinBox_Komi.setMaximum(1444.0)
        self.doubleSpinBox_Komi.setProperty("value", 6.5)
        self.doubleSpinBox_Komi.setObjectName("doubleSpinBox_Komi")
        self.horizontalLayout.addWidget(self.doubleSpinBox_Komi)
        self.layoutWidget1 = QtWidgets.QWidget(self.page_CreateSGF)
        self.layoutWidget1.setGeometry(QtCore.QRect(62, 150, 261, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_WhiteName = QtWidgets.QLabel(self.layoutWidget1)
        self.label_WhiteName.setMinimumSize(QtCore.QSize(201, 19))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_WhiteName.setFont(font)
        self.label_WhiteName.setStyleSheet("QLabel {\n"
                                           "    font-size: 16px;\n"
                                           "    font-weight: bold;\n"
                                           "    color: #2E8B57; /* Sea green */\n"
                                           "    padding: 5px;\n"
                                           "}")
        self.label_WhiteName.setObjectName("label_WhiteName")
        self.verticalLayout.addWidget(self.label_WhiteName)
        self.lineEdit_WhiteName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_WhiteName.setMinimumSize(QtCore.QSize(201, 24))
        self.lineEdit_WhiteName.setMaximumSize(QtCore.QSize(201, 24))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_WhiteName.setFont(font)
        self.lineEdit_WhiteName.setAutoFillBackground(False)
        self.lineEdit_WhiteName.setStyleSheet("background: none;")
        self.lineEdit_WhiteName.setObjectName("lineEdit_WhiteName")
        self.verticalLayout.addWidget(self.lineEdit_WhiteName)
        self.label_BlackName = QtWidgets.QLabel(self.layoutWidget1)
        self.label_BlackName.setMinimumSize(QtCore.QSize(201, 19))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_BlackName.setFont(font)
        self.label_BlackName.setObjectName("label_BlackName")
        self.verticalLayout.addWidget(self.label_BlackName)
        self.lineEdit_BlackName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_BlackName.setMinimumSize(QtCore.QSize(201, 24))
        self.lineEdit_BlackName.setMaximumSize(QtCore.QSize(201, 24))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_BlackName.setFont(font)
        self.lineEdit_BlackName.setAutoFillBackground(False)
        self.lineEdit_BlackName.setStyleSheet("background: none;")
        self.lineEdit_BlackName.setObjectName("lineEdit_BlackName")
        self.verticalLayout.addWidget(self.lineEdit_BlackName)
        self.stackedWidget.addWidget(self.page_CreateSGF)
        self.page_PlayWithBot = QtWidgets.QWidget()
        self.page_PlayWithBot.setObjectName("page_PlayWithBot")
        self.widget_PvsB = QtWidgets.QWidget(self.page_PlayWithBot)
        self.widget_PvsB.setGeometry(QtCore.QRect(170, 150, 771, 311))
        self.widget_PvsB.setStyleSheet("QWidget#widget_PvsB{\n"
                                       "border-radius: 10px;\n"
                                       "border: 1px solid grey\n"
                                       "}")
        self.widget_PvsB.setObjectName("widget_PvsB")
        self.layoutWidget2 = QtWidgets.QWidget(self.widget_PvsB)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 30, 733, 283))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_3 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 1)
        self.pushButton_PlayWithBotOk = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_PlayWithBotOk.setStyleSheet("QPushButton {\n"
                                                    "                background-color: #5A9; \n"
                                                    "                color: white; \n"
                                                    "                padding: 10px 20px; \n"
                                                    "                border: 2px solid #476;\n"
                                                    "                border-radius: 10px;\n"
                                                    "                font-size: 16px;\n"
                                                    "                font-weight: bold;\n"
                                                    "                box-shadow: 3px 3px 5px #888888;\n"
                                                    "                transition: background-color 0.3s, transform 0.3s;\n"
                                                    "margin:10px;\n"
                                                    "            }\n"
                                                    "            QPushButton:hover {\n"
                                                    "                background-color: #476;\n"
                                                    "                transform: scale(1.05);\n"
                                                    "            }\n"
                                                    "            QPushButton:pressed {\n"
                                                    "                background-color: #354;\n"
                                                    "                transform: scale(0.95);\n"
                                                    "            }")
        self.pushButton_PlayWithBotOk.setObjectName("pushButton_PlayWithBotOk")
        self.gridLayout.addWidget(self.pushButton_PlayWithBotOk, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_PlayerColor = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_PlayerColor.setFont(font)
        self.label_PlayerColor.setStyleSheet("QLabel {\n"
                                             "                font-size: 24px;\n"
                                             "                font-weight: bold;\n"
                                             "                color: rgb(70, 70, 70);\n"
                                             "                padding: 10px;\n"
                                             "            }")
        self.label_PlayerColor.setObjectName("label_PlayerColor")
        self.verticalLayout_3.addWidget(self.label_PlayerColor, 0, QtCore.Qt.AlignHCenter)
        self.radioButton_Black = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Black.setFont(font)
        self.radioButton_Black.setStyleSheet("/* QRadioButton Styles */\n"
                                             "QRadioButton {\n"
                                             "       font-size: 24px;\n"
                                             "                font-weight: bold;\n"
                                             "                color: rgb(70, 70, 70);\n"
                                             "                padding: 10px;\n"
                                             "                background-color: #F0F0F0;\n"
                                             "    color: #5A9; \n"
                                             "    padding: 5px;\n"
                                             "}\n"
                                             "\n"
                                             "QRadioButton::indicator {\n"
                                             "    width: 15px;\n"
                                             "    height: 15px;\n"
                                             "    border-radius: 7.5px;\n"
                                             "}\n"
                                             "\n"
                                             "QRadioButton::indicator::unchecked {\n"
                                             "    border: 2px solid #2E8B57;\n"
                                             "    background-color: #FFFFFF;\n"
                                             "}\n"
                                             "\n"
                                             "QRadioButton::indicator::checked {\n"
                                             "    border: 2px solid #2E8B57;\n"
                                             "    background-color: #5A9; \n"
                                             "}")
        self.radioButton_Black.setObjectName("radioButton_Black")
        self.verticalLayout_3.addWidget(self.radioButton_Black, 0, QtCore.Qt.AlignHCenter)
        self.radioButton_White = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_White.setFont(font)
        self.radioButton_White.setStyleSheet("/* QRadioButton Styles */\n"
                                             "QRadioButton {\n"
                                             "       font-size: 24px;\n"
                                             "                font-weight: bold;\n"
                                             "                color: rgb(70, 70, 70);\n"
                                             "                padding: 10px;\n"
                                             "                background-color: #F0F0F0;\n"
                                             "    color: #5A9; \n"
                                             "    padding: 5px;\n"
                                             "}\n"
                                             "\n"
                                             "QRadioButton::indicator {\n"
                                             "    width: 15px;\n"
                                             "    height: 15px;\n"
                                             "    border-radius: 7.5px;\n"
                                             "}\n"
                                             "\n"
                                             "QRadioButton::indicator::unchecked {\n"
                                             "    border: 2px solid #2E8B57;\n"
                                             "    background-color: #FFFFFF;\n"
                                             "}\n"
                                             "\n"
                                             "QRadioButton::indicator::checked {\n"
                                             "    border: 2px solid #2E8B57;\n"
                                             "    background-color: #5A9; \n"
                                             "}")
        self.radioButton_White.setObjectName("radioButton_White")
        self.verticalLayout_3.addWidget(self.radioButton_White, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.layoutWidget2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_OpponentBot = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.comboBox_OpponentBot.setFont(font)
        self.comboBox_OpponentBot.setAutoFillBackground(False)
        self.comboBox_OpponentBot.setStyleSheet("/* QComboBox Styles */\n"
                                                "QComboBox {\n"
                                                "    font-size: 24px;\n"
                                                "    padding: 5px;\n"
                                                "    border: 2px solid #5A9;\n"
                                                "    border-radius: 5px;\n"
                                                "                color: rgb(70, 70, 70);\n"
                                                "margin:20px;\n"
                                                "}\n"
                                                "\n"
                                                "QComboBox QAbstractItemView {\n"
                                                "    border: 2px solid rgb(40,40,40);\n"
                                                "    selection-background-color:#5A9;\n"
                                                "}")
        self.comboBox_OpponentBot.setFrame(True)
        self.comboBox_OpponentBot.setObjectName("comboBox_OpponentBot")
        self.comboBox_OpponentBot.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_OpponentBot)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.label_CreateSGF_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_CreateSGF_2.setMinimumSize(QtCore.QSize(731, 41))
        self.label_CreateSGF_2.setStyleSheet("QLabel {\n"
                                             "                font-size: 24px;\n"
                                             "                font-weight: bold;\n"
                                             "                color: rgb(70, 70, 70);\n"
                                             "            }")
        self.label_CreateSGF_2.setScaledContents(True)
        self.label_CreateSGF_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CreateSGF_2.setWordWrap(True)
        self.label_CreateSGF_2.setObjectName("label_CreateSGF_2")
        self.gridLayout.addWidget(self.label_CreateSGF_2, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_PlayWithBot)
        self.page_bot_vs_bot = QtWidgets.QWidget()
        self.page_bot_vs_bot.setObjectName("page_bot_vs_bot")
        self.widget_BvsB = QtWidgets.QWidget(self.page_bot_vs_bot)
        self.widget_BvsB.setGeometry(QtCore.QRect(170, 150, 771, 341))
        self.widget_BvsB.setStyleSheet("QWidget#widget_BvsB{\n"
                                       "border-radius: 10px;\n"
                                       "border: 1px solid grey\n"
                                       "}")
        self.widget_BvsB.setObjectName("widget_BvsB")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget_BvsB)
        self.layoutWidget_2.setGeometry(QtCore.QRect(12, 12, 751, 311))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_CreateSGF_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_CreateSGF_4.setStyleSheet("QLabel {\n"
                                             "                font-size: 24px;\n"
                                             "                font-weight: bold;\n"
                                             "                color: rgb(70, 70, 70);\n"
                                             "            }")
        self.label_CreateSGF_4.setScaledContents(True)
        self.label_CreateSGF_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CreateSGF_4.setWordWrap(True)
        self.label_CreateSGF_4.setObjectName("label_CreateSGF_4")
        self.gridLayout_2.addWidget(self.label_CreateSGF_4, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.pushButton_BotVsBotOK = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_BotVsBotOK.setStyleSheet("QPushButton {\n"
                                                 "                background-color: #5A9; \n"
                                                 "                color: white; \n"
                                                 "                padding: 10px 20px; \n"
                                                 "                border: 2px solid #476;\n"
                                                 "                border-radius: 10px;\n"
                                                 "                font-size: 16px;\n"
                                                 "                font-weight: bold;\n"
                                                 "                box-shadow: 3px 3px 5px #888888;\n"
                                                 "                transition: background-color 0.3s, transform 0.3s;\n"
                                                 "margin:20px;\n"
                                                 "            }\n"
                                                 "            QPushButton:hover {\n"
                                                 "                background-color: #476;\n"
                                                 "                transform: scale(1.05);\n"
                                                 "            }\n"
                                                 "            QPushButton:pressed {\n"
                                                 "                background-color: #354;\n"
                                                 "                transform: scale(0.95);\n"
                                                 "            }")
        self.pushButton_BotVsBotOK.setObjectName("pushButton_BotVsBotOK")
        self.gridLayout_2.addWidget(self.pushButton_BotVsBotOK, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_BlackName_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_BlackName_2.setMinimumSize(QtCore.QSize(201, 19))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_BlackName_2.setFont(font)
        self.label_BlackName_2.setStyleSheet("QLabel {\n"
                                             "                font-size: 24px;\n"
                                             "                font-weight: bold;\n"
                                             "                color: rgb(70, 70, 70);\n"
                                             "            }")
        self.label_BlackName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BlackName_2.setObjectName("label_BlackName_2")
        self.verticalLayout_5.addWidget(self.label_BlackName_2, 0, QtCore.Qt.AlignHCenter)
        self.comboBox_BlackBot = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_BlackBot.setAutoFillBackground(False)
        self.comboBox_BlackBot.setStyleSheet("/* QComboBox Styles */\n"
                                             "QComboBox {\n"
                                             "    font-size: 24px;\n"
                                             "    padding: 5px;\n"
                                             "    border: 2px solid #5A9;\n"
                                             "    border-radius: 5px;\n"
                                             "                color: rgb(70, 70, 70);\n"
                                             "margin:20px;\n"
                                             "}\n"
                                             "\n"
                                             "QComboBox QAbstractItemView {\n"
                                             "    border: 2px solid rgb(40,40,40);\n"
                                             "    selection-background-color:#5A9;\n"
                                             "}")
        self.comboBox_BlackBot.setFrame(True)
        self.comboBox_BlackBot.setObjectName("comboBox_BlackBot")
        self.comboBox_BlackBot.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_BlackBot)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_WhiteName_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_WhiteName_2.setMinimumSize(QtCore.QSize(201, 19))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_WhiteName_2.setFont(font)
        self.label_WhiteName_2.setStyleSheet("QLabel {\n"
                                             "                font-size: 24px;\n"
                                             "                font-weight: bold;\n"
                                             "                color: rgb(70, 70, 70);\n"
                                             "            }")
        self.label_WhiteName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WhiteName_2.setObjectName("label_WhiteName_2")
        self.verticalLayout_6.addWidget(self.label_WhiteName_2, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.comboBox_WhiteBot = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_WhiteBot.setAutoFillBackground(False)
        self.comboBox_WhiteBot.setStyleSheet("/* QComboBox Styles */\n"
                                             "QComboBox {\n"
                                             "    font-size: 24px;\n"
                                             "    padding: 5px;\n"
                                             "    border: 2px solid #5A9;\n"
                                             "    border-radius: 5px;\n"
                                             "                color: rgb(70, 70, 70);\n"
                                             "margin:20px;\n"
                                             "}\n"
                                             "\n"
                                             "QComboBox QAbstractItemView {\n"
                                             "    border: 2px solid rgb(40,40,40);\n"
                                             "    selection-background-color:#5A9;\n"
                                             "}")
        self.comboBox_WhiteBot.setFrame(True)
        self.comboBox_WhiteBot.setObjectName("comboBox_WhiteBot")
        self.comboBox_WhiteBot.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_WhiteBot)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 5, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_bot_vs_bot)
        self.pushButton_EditSGF = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_EditSGF.setEnabled(False)
        self.pushButton_EditSGF.setGeometry(QtCore.QRect(990, 70, 120, 40))
        self.pushButton_EditSGF.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton_EditSGF.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_EditSGF.setFont(font)
        self.pushButton_EditSGF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_EditSGF.setText("")
        self.pushButton_EditSGF.setAutoDefault(False)
        self.pushButton_EditSGF.setDefault(False)
        self.pushButton_EditSGF.setFlat(True)
        self.pushButton_EditSGF.setObjectName("pushButton_EditSGF")
        self.pushButton_CreateSGF = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CreateSGF.setEnabled(True)
        self.pushButton_CreateSGF.setGeometry(QtCore.QRect(1040, 20, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_CreateSGF.setFont(font)
        self.pushButton_CreateSGF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_CreateSGF.setText("")
        self.pushButton_CreateSGF.setAutoDefault(False)
        self.pushButton_CreateSGF.setDefault(False)
        self.pushButton_CreateSGF.setFlat(True)
        self.pushButton_CreateSGF.setObjectName("pushButton_CreateSGF")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox_OpponentBot.setCurrentIndex(0)
        self.comboBox_BlackBot.setCurrentIndex(0)
        self.comboBox_WhiteBot.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_BotVBot.setText(_translate("MainWindow", "Bot VS Bot"))
        self.pushButton_AboutGo.setText(_translate("MainWindow", "About GO"))
        self.pushButton_PlayerVSBot.setText(_translate("MainWindow", "Play with Bot"))
        self.label.setText(_translate("MainWindow", "Welcome to my Go testing App - Choose your options!"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15.75pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:90%;\"><span style=\" font-family:\'Aptos\'; font-size:17pt; color:#000000;\">Go is an ancient Chinese strategy game</span><span style=\" font-size:16pt;\"> </span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15.75pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:90%;\"><span style=\" font-family:\'Aptos\'; font-size:17pt; color:#000000;\">The goal is to surround board points and enemy stones to capture them. </span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15.75pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:90%;\"><span style=\" font-family:\'Aptos\'; font-size:17pt; color:#000000;\">Go was labeled as a great challenge for AI due to its great computational complexity</span><span style=\" font-size:16pt;\"> </span></p></body></html>"))
        self.label_CreateSGF.setText(_translate("MainWindow", "Create SGF "))
        self.pushButton_CreateOk.setText(_translate("MainWindow", "Ok"))
        self.label_4.setText(_translate("MainWindow", "Board Size"))
        self.label_5.setText(_translate("MainWindow", "Handicap"))
        self.label_6.setText(_translate("MainWindow", "Komi "))
        self.label_WhiteName.setText(_translate("MainWindow", "White Player\'s Name"))
        self.lineEdit_WhiteName.setPlaceholderText(_translate("MainWindow", "White"))
        self.label_BlackName.setText(_translate("MainWindow", "Black Player\'s Name "))
        self.lineEdit_BlackName.setPlaceholderText(_translate("MainWindow", "Black"))
        self.pushButton_PlayWithBotOk.setText(_translate("MainWindow", "Start"))
        self.label_PlayerColor.setText(_translate("MainWindow", "Your Color"))
        self.radioButton_Black.setText(_translate("MainWindow", "Black"))
        self.radioButton_White.setText(_translate("MainWindow", "White"))
        self.comboBox_OpponentBot.setCurrentText(_translate("MainWindow", "Choose Opponent"))
        self.comboBox_OpponentBot.setItemText(0, _translate("MainWindow", "Choose Opponent"))
        self.label_CreateSGF_2.setText(_translate("MainWindow", "Play With Bot"))
        self.label_CreateSGF_4.setText(_translate("MainWindow", "Bot against Bot game"))
        self.pushButton_BotVsBotOK.setText(_translate("MainWindow", "Start"))
        self.label_BlackName_2.setText(_translate("MainWindow", "Black Bot"))
        self.comboBox_BlackBot.setCurrentText(_translate("MainWindow", "Drop down to choose"))
        self.comboBox_BlackBot.setItemText(0, _translate("MainWindow", "Drop down to choose"))
        self.label_WhiteName_2.setText(_translate("MainWindow", "White Bot"))
        self.comboBox_WhiteBot.setCurrentText(_translate("MainWindow", "Drop down to choose"))
        self.comboBox_WhiteBot.setItemText(0, _translate("MainWindow", "Drop down to choose"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
