# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\designs\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1576, 1006)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_GoBoard = QtWidgets.QWidget(self.centralwidget)
        self.widget_GoBoard.setGeometry(QtCore.QRect(20, 60, 900, 900))
        self.widget_GoBoard.setMinimumSize(QtCore.QSize(800, 800))
        self.widget_GoBoard.setMaximumSize(QtCore.QSize(900, 900))
        self.widget_GoBoard.setObjectName("widget_GoBoard")
        self.graphicsView_GoBoard = QtWidgets.QGraphicsView(self.widget_GoBoard)
        self.graphicsView_GoBoard.setGeometry(QtCore.QRect(0, 0, 900, 900))
        self.graphicsView_GoBoard.setMinimumSize(QtCore.QSize(900, 900))
        self.graphicsView_GoBoard.setMaximumSize(QtCore.QSize(900, 900))
        self.graphicsView_GoBoard.setObjectName("graphicsView_GoBoard")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 901, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_Move = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Move.setObjectName("label_Move")
        self.horizontalLayout.addWidget(self.label_Move, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_MoveNumber = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_MoveNumber.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_MoveNumber.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_MoveNumber.setAutoFillBackground(False)
        self.lineEdit_MoveNumber.setFrame(False)
        self.lineEdit_MoveNumber.setObjectName("lineEdit_MoveNumber")
        self.horizontalLayout.addWidget(self.lineEdit_MoveNumber, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_CurrentPlayer = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_CurrentPlayer.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_CurrentPlayer.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_CurrentPlayer.setFrame(False)
        self.lineEdit_CurrentPlayer.setObjectName("lineEdit_CurrentPlayer")
        self.horizontalLayout.addWidget(self.lineEdit_CurrentPlayer)
        self.lineEdit_MoveCoords = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_MoveCoords.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_MoveCoords.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_MoveCoords.setFrame(False)
        self.lineEdit_MoveCoords.setObjectName("lineEdit_MoveCoords")
        self.horizontalLayout.addWidget(self.lineEdit_MoveCoords)
        self.lineEdit_NextPlayer = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_NextPlayer.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_NextPlayer.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_NextPlayer.setFrame(False)
        self.lineEdit_NextPlayer.setObjectName("lineEdit_NextPlayer")
        self.horizontalLayout.addWidget(self.lineEdit_NextPlayer)
        self.label_NextPlyer = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_NextPlyer.setObjectName("label_NextPlyer")
        self.horizontalLayout.addWidget(self.label_NextPlyer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1576, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Move.setText(_translate("MainWindow", "Move "))
        self.label_NextPlyer.setText(_translate("MainWindow", "to play"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
